### ISSUE TITLE
FANZAからの情報取得失敗

### ISSUE THREAD

**Issue by tsu-nera** [tsu-nera/kotori#351]
- [x] bf00638
- [x] 1havd01011
- [x] 18sprd01450
- [x] 172real00745
- [x] h_275tdbr00075
- [x] h_086jura00039
- [ ] stcead00040 -> //cc3001.dmm.co.jp/litevideo/freepv/c/cea/cead00212/cead00212_dmb_w.mp4 これはむり
- [x] TypeError: __init__() missing 1 required positional argument: 'reason'

---

なるべく早く調査する

```
2021-08-25 15:31:13,597 ERROR   : failed to get video file
['https://cc3001.dmm.co.jp/litevideo/freepv/b/bf/bf00638/bf00638_mhb_w.mp4', 'https://cc3001.dmm.co.jp/litevideo/freepv/b/bf/bf638/bf638_mhb_w.mp4', 'https://cc3001.dmm.co.jp/litevideo/freepv/b/bf/bf00638/bf00638_mhb_s.mp4', 'https://cc3001.dmm.co.jp/litevideo/freepv/b/bf/bf638/bf638_mhb_s.mp4', 'https://cc3001.dmm.co.jp/litevideo/freepv/b/bf/bf00638/bf00638_dmb_w.mp4', 'https://cc3001.dmm.co.jp/litevideo/freepv/b/bf/bf638/bf638_dmb_w.mp4', 'https://cc3001.dmm.co.jp/litevideo/freepv/b/bf/bf00638/bf00638_dmb_s.mp4', 'https://cc3001.dmm.co.jp/litevideo/freepv/b/bf/bf638/bf638_dmb_s.mp4', 'https://cc3001.dmm.co.jp/litevideo/freepv/b/bf/bf00638/bf00638_dm_w.mp4', 'https://cc3001.dmm.co.jp/litevideo/freepv/b/bf/bf638/bf638_dm_w.mp4', 'https://cc3001.dmm.co.jp/litevideo/freepv/b/bf/bf00638/bf00638_dm_s.mp4', 'https://cc3001.dmm.co.jp/litevideo/freepv/b/bf/bf638/bf638_dm_s.mp4', 'https://cc3001.dmm.co.jp/litevideo/freepv/b/bf/bf00638/bf00638_sm_w.mp4', 'https://cc3001.dmm.co.jp/litevideo/freepv/b/bf/bf638/bf638_sm_w.mp4', 'https://cc3001.dmm.co.jp/litevideo/freepv/b/bf/bf00638/bf00638_sm_s.mp4', 'https://cc3001.dmm.co.jp/litevideo/freepv/b/bf/bf638/bf638_sm_s.mp4']
https://www.dmm.co.jp/litevideo/-/part/=/cid=bf00638/size=720_480/
bf00638
2021-08-25 15:31:13,599 ERROR   : cannot unpack non-iterable NoneType object
Traceback (most recent call last):
  File "/home/ubuntu/repo/fbot/fbot-4191/src/tasks/twitter.py", line 30, in post
    status, params = video.post_video_by_cid(cid, MODE_CRAWLER)
TypeError: cannot unpack non-iterable NoneType object
2021-08-25 15:31:13,622 DEBUG   : sleep until next interval: 80 min
```

**Comment by tsu-nera** [comment]
maker codeが2digitsというのは怪しいな。

**Comment by tsu-nera** [comment]
cid=18sprd01450     

これも。ついでに追加実装した例外処理がうまく動いていないので調べる。

 FanzaContentsParseError() 多分引数なしが原因。

```
2021-08-28 18:13:03,659 INFO    : post tweet start: fbot=fbot-4193, cid=18sprd01450                                                                                                                                              
2021-08-28 18:13:03,851 DEBUG   : 代理出産の母 佐倉由美子 佐倉由美子                                                                                                                                                             
2021-08-28 18:13:04,103 ERROR   : failed to get video file                                                                                                                                                                       
['https://cc3001.dmm.co.jp/litevideo/freepv/1/18s/18sprd01450/18sprd01450_mhb_w.mp4', 'https://cc3001.dmm.co.jp/litevideo/freepv/1/18s/18sprd01450/18sprd01450_mhb_s.mp4', 'https://cc3001.dmm.co.jp/litevideo/freepv/1/18s/18spr
d01450/18sprd01450_dmb_w.mp4', 'https://cc3001.dmm.co.jp/litevideo/freepv/1/18s/18sprd01450/18sprd01450_dmb_s.mp4', 'https://cc3001.dmm.co.jp/litevideo/freepv/1/18s/18sprd01450/18sprd01450_dm_w.mp4', 'https://cc3001.dmm.co.jp
/litevideo/freepv/1/18s/18sprd01450/18sprd01450_dm_s.mp4', 'https://cc3001.dmm.co.jp/litevideo/freepv/1/18s/18sprd01450/18sprd01450_sm_w.mp4', 'https://cc3001.dmm.co.jp/litevideo/freepv/1/18s/18sprd01450/18sprd01450_sm_s.mp4'
]                                                                                                                                                                                                                                
https://www.dmm.co.jp/litevideo/-/part/=/cid=18sprd01450/size=720_480/                                                                                                                                                           
18sprd01450
2021-08-28 18:13:04,105 ERROR   : unknown error occured during post tweet!!!: fbot=fbot-4193, cid=18sprd01450
Traceback (most recent call last):
  File "/home/ubuntu/repo/fbot/staging/src/tasks/twitter.py", line 31, in post_latest
    params = video.post_video_by_cid(cid, MODE_CRAWLER)
  File "/home/ubuntu/repo/fbot/staging/src/utils/video.py", line 168, in post_video_by_cid
    raise FanzaContentsParseError()
TypeError: __init__() missing 1 required positional argument: 'reason'
```

**Comment by tsu-nera** [comment]
maker_idが4桁の場合は上の1つだけ削られるケースがあるのか...

**Comment by tsu-nera** [comment]
動画が存在するだけのpingコマンド的なものが欲しい。HEAD requestとか使えるのかな？getではなくて

**Comment by tsu-nera** [comment]
どうしても例外があり、ある程度は諦める。古いものを取得しようとしたらないことがあるが、新しいものから取得すれば発生頻度はすくないはず。
