### ISSUE TITLE
watchdogbotでProxyError発生

### ISSUE THREAD

**Issue by tsu-nera** [tsu-nera/kotori#355]
Proxyへの通信エラー発生？？

```
  File "/home/ubuntu/miniconda3/envs/fanza/lib/python3.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)                    
  File "/home/ubuntu/miniconda3/envs/fanza/lib/python3.7/site-packages/requests/adapters.py", line 510, in send
    raise ProxyError(e, request=request)                   
requests.exceptions.ProxyError: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/search/adaptive.json?q=from%3A%40xxxx&count=20&spelling_corrections=0&tweet_search_mode=live (Caused by Pro
xyError('Cannot connect to proxy.', OSError(0, 'Error')))
```

**Comment by tsu-nera** [comment]
再度試してもsocket timeout 

```
Traceback (most recent call last):                                                                                                                                                                                                            
  File "/home/ubuntu/miniconda3/envs/fanza/lib/python3.7/site-packages/urllib3/connectionpool.py", line 667, in urlopen                                                                                                                       
    self._prepare_proxy(conn)                                                                                                                                                                                                                 
  File "/home/ubuntu/miniconda3/envs/fanza/lib/python3.7/site-packages/urllib3/connectionpool.py", line 932, in _prepare_proxy                                                                                                                
    conn.connect()                                                                                                                                                                                                                            
  File "/home/ubuntu/miniconda3/envs/fanza/lib/python3.7/site-packages/urllib3/connection.py", line 317, in connect
    self._tunnel()
  File "/home/ubuntu/miniconda3/envs/fanza/lib/python3.7/http/client.py", line 922, in _tunnel
    (version, code, message) = response._read_status()
  File "/home/ubuntu/miniconda3/envs/fanza/lib/python3.7/http/client.py", line 271, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/home/ubuntu/miniconda3/envs/fanza/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

```
