### ISSUE TITLE
proxy ip変更でtwitter メディアアップロード失敗

### ISSUE THREAD

**Issue by tsu-nera** [tsu-nera/kotori#359]
ツイートはできる、メディアアップロードはできない。wirte権限は問題ない？

確認事項
- [x] 別IPでも失敗するか？(-> 無闇に別IPからアクセスしたくないので保留)
- [x] API Keyやアクセストークンを再作成しても失敗するか？
- [x] appのアクセスを設定画面から削除して再度やって挙動に変化があるか？
- [x] tweepyとpython-twitterで挙動に違いはあるか？
- [ ] apiからでなくてブラウザから失敗するか？
- [ ] 既知障害をネットで検索する

# crash log

```
requests.exceptions.ProxyError: HTTPSConnectionPool(host='upload.twitter.com', port=443): Max retries exceeded with url: /1.1/media/upload.json (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fea413d9b10>: Failed to establish a new connection: [Errno 110] Connection timed out')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/repo/fbot/develop/src/tasks/twitter.py", line 30, in post
    status, params = video.post_video_by_cid(cid, MODE_CRAWLER)
  File "/home/ubuntu/repo/fbot/develop/src/utils/video.py", line 177, in post_video_by_cid
    video.video4upload_path)
  File "/home/ubuntu/repo/fbot/develop/src/libs/twitter_client.py", line 54, in post_with_media
    code = int(e[0]["code"])
TypeError: 'ProxyError' object is not subscriptable
```

**Comment by tsu-nera** [comment]
python-twitterでメディアアップロードをするのをやめて、apiを元にrequestsライブラリのみで実装して解決した。
