### ISSUE TITLE
metricsのクローリングで例外発生

### ISSUE THREAD

**Issue by tsu-nera** [tsu-nera/kotori#451]
error reportingからgithub issuse作成とdiscord通知が連携できないかな？

https://console.cloud.google.com/errors?time=P7D&order=COUNT_DESC&resolution=OPEN&resolution=ACKNOWLEDGED&project=dmm-fanza&folder&hl=ja&organizationId

```
Traceback (most recent call last):
  File "/home/ubuntu/repo/fbot/watchdog/src/bots/watchdog_bot.py", line 53, in crawl_fbot_metrics
    self.fbot_crawler.crawl_metrics()
  File "/home/ubuntu/repo/fbot/watchdog/src/crawlers/fbot_crawler.py", line 168, in crawl_metrics
    user_id = str(metrics['user_id'])
KeyError: 'user_id'
```

**Comment by tsu-nera** [comment]
Cloud Monitoringで通知をwebhookでおくれそうだけど、動かないな

**Comment by tsu-nera** [comment]
issueにするか...

**Comment by tsu-nera** [comment]
とりあえずクラッシュは再発しないので様子見
